# Mongodb configuration
spring.data.mongodb.uri=mongodb+srv://3343dattaram_db_user:MdxuPd1Jlq5ZFFju@resume0.xzul0cb.mongodb.net/resumebuilder

# Email configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=b42554001@smtp-brevo.com
spring.mail.password=${BREVO_PASSWORD:bskExkPasrFRoZG}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=dattaramm91@gmail.com

# Application info
app.base.url=http://localhost:8080

# Cloudinary information
cloudinary.cloud-name=dvy9fzwz
cloudinary.api-key=873832711849868
cloudinary.api-secret=${CLOUDINARY_APISECRET:IsIIOCOSOLHOyP8osvcjRucFSTc}

# JWT Configuration
jwt.secret=your-secret-key-here-change-this-in-production-with-more-secure-and-complicated-key
jwt.expiration=604800000

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY}
razorpay.key.secret=${RAZORPAY_SECRET}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration